#include <stdio.h>
#include <conio.h>


int main() {
    
    int i,rand,guess;
    clrscr();
    int no_of_guess=0;
    printf("Enter the previous random no.\n\tor\nif you got nothing with you, just enter any number:");
    scanf("%d", &rand);
    printf("\n\n---------Thank God for choosing that number---------bery nice\n");
    rand= ((rand*37) % 100) + 1;
    printf("\nNOW, your CHALLENGE begins.......\nThe question is...\tcan you guess the pseudo random number generated by my algorithm-------//mewhehehe[evil laugh], yes!!!!!...my own algorithm.\n");
    printf("\n[smirks] Guess the next number now, you ugly bitch:");
    scanf("%d",&guess);
    no_of_guess++;

    for(no_of_guess=1;guess!=rand;no_of_guess++){
      printf("\nUghhh.., I saw that coming...\n");
      for( i=2;i<=no_of_guess;i++){
        printf("again!!\n");
      }
      if(guess<rand){
        printf("\nnumbers are till 100, bruh");
        for(i=2;i<=no_of_guess;i++){
            printf("hhh");
        }
        for(i=2;i<=no_of_guess;i++){
            printf("!!");
        }
        printf("\nTry l-a-r-g-e-r");
        for(i=2;i<=no_of_guess;i++){
            printf("rr");
        }
        printf(" than %d,now",guess);
        
      }                                //this is past  amarjeet[time:-12:50am], dear comrade: if you ever wonder what typa shit the future amarjeet sent you, just take a moment of breathe.
                                       //AND kindly, keep that doubt to almighty yourself only, coz' even i made this with prayers, how the hell is he supposed to know how this shit works, sybau.
      if(guess>rand){
        printf("\nWe ain't going to moo");
        for(i=2;i<=no_of_guess;i++){
            printf("000");
        }
        printf("n");
        printf("\nTry s-m-a-l-l-e-r");
        for(i=2;i<=no_of_guess;i++){
            printf("rr");
        }
        printf(" than %d,now",guess);
        
      }
      printf("\nTry again:");
      scanf("%d",&guess);
        
    }
    if(no_of_guess<=2){
        printf("\n OMG the hacker's in the hood, impressive\n----guessed right----\n");
    }
    else if(no_of_guess>2 && no_of_guess <=5){
        printf("\nahnnn.., not bad, not bad: well done---that's the number\n");

    }
    else{
        printf("\n damnnn, you're cooked bro!!\n........ you took %d fucking attempts just to guess a number\n",no_of_guess);
        printf("\n....[personal advice]: turn off your laptop.... go to nature and chill\n");
        printf("_______lyf is BEAUTIFUL, do something else(anything except guessing)\n");
    }
 getch();
    return 0;
}
